#!/bin/bash
# Format YouTube download data as HTML

jq -r '"<!DOCTYPE html>
<html lang=\"en\">
  <head>
    <meta charset=\"utf-8\" />
    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\" integrity=\"sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7\" crossorigin=\"anonymous\">
  </head>
  <body>

  <div class=\"container\">

  Comments for YouTube video <a href=\"https://www.youtube.com/watch?v=\(.videoId)\">\(.videoId)</a>

  There are \(.topLevelCommentCount) top level comments and
  \(.commentCount) comments in total.

  <table class=\"table\">
    <thead>
      <tr>
        <td>Date</td>
        <td>Author</td>
        <td>Comment</td>
      </tr>
    </thead>
    <tbody>" +

 ([.comments[] | "
  <tr>
    <td>\(.date)</td>
    <td>\(.author)</td>
    <td>
      <a href=\"https://www.youtube.com/watch?v=\(.videoId)&lc=\(.id)\">\(.comment)</a>
      <p>
        <strong>\(.likeCount) likes</strong> and
        <strong>\(.replyCount) replies</strong>
      </p>
      <table class=\"table\">" + ([.replies |
          if length <= 0 then
            ""
          else
            (.[] | "
              <tr>
              <td>\(.comment)<p><strong>\(.likeCount) likes</strong></p></td>
                <td>\(.author)</td>
              </tr>
              ")
              end] | join("")) + "
      </table>
    </td>
  </tr>
  "] | join("")) + "
    </tbody>
    </div>
  </body>
</html>"'
